name: Add to project
on:
  issues:
    types: [opened, reopened, labeled]
  pull_request:
    types: [opened, reopened, labeled]
jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.0
        with:
          project-url: https://github.com/users/scheidydude/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
